// <auto-generated />
using System;
using CouponAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CouponAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity("CouponAPI.Models.Couponcode", b =>
                {
                    b.Property<int>("CoupounId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<int?>("Discount");

                    b.Property<int?>("Noofcustomer");

                    b.Property<int?>("Paynoofcustomer");

                    b.Property<long?>("Totalamount");

                    b.HasKey("CoupounId");

                    b.ToTable("CouponCodes");
                });
#pragma warning restore 612, 618
        }
    }
}
